version: "2"

services:
  db:
    image: mysql:8.0.15
    volumes:
      - ./app_data:/var/lib/mysql
    ports:
      - "3360:3360"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: app
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: app

  nginx-node:
      restart: always
      image: finizco/nginx-node:latest
      ports:
        - "8080:8080"
      environment:
        - NODE_PORT=3000
        - NODE_MODE=prod
      volumes:
        - ./code:/app
      working_dir: /app
      depends_on:
        - db